RsaCtfTool/RsaCtfTool

RsaCtfTool.py
Initializes the P and Q in `self.pub_key` if nonexistent and only tries to unpack the results if returned value is long enough.
Also removes unnecessary whitespaces from the code.
Fixes: #10
=> Fix a bug in Pollard_p_1 when 0 is returned

README.md, RsaCtfTool.py
In this commit, I write a line. If the python version is below 3.0, it will overwrite `int` by `long` so that python2 is still supported.
It is ugly, but it just a suggestion that you either support python2 in an ugly way or at least you should tell people python2 is no longer supported.
=> update `uncipher` to `uncipherfile` in README and a suggestion

RsaCtfTool.py
Error is generated when no command line arguments are provided:
```
File "C:\Python27\RsaCtfTool\RsaCtfTool.py", line 103, in init
if '*' in args.publickey or '?' in args.publickey:
TypeError: argument of type 'NoneType' is not iterable]
```
This commit checks the length of sys.argv to see if command line arguments have been provided. If not, it prints the help message and exits.
=> Fix for issue #22

siqs.py
TypeError exception occurred when using siqs attacking method
```
./RsaCtfTool.py --publickey pub.pem --private --attack siqs
```
```
Traceback (most recent call last):
File "./RsaCtfTool.py", line 725, in <module>
attackobj.attack()
File "./RsaCtfTool.py", line 519, in attack
getattr(self, attack.__name__)()
File "./RsaCtfTool.py", line 449, in siqs
siqsobj.doattack()
File "/usr/home/hyili/python-env/RsaCtfTool/siqs.py", line 78, in doattack
if re.search('^P[0-9]+\ =\ [0-9]+$', line):
File "/usr/local/lib/python3.6/re.py", line 182, in search
return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```
=> Fix py2 to py3 migration problem in siqs function

README.md
This somewhat enhances readability.
=> Use code blocks for Kali instructions

RsaCtfTool.py
Since in the CSAW CTF 2018 Finals there was a challenge requiring Wiener's attack (which I didn't know to this timepoint), I just ran RsaCtfTool. Unfortunately, sympy was not installed - and I was not aware of it. I thought wieners attack run unsuccesfully, but instead it didn't run at all.
I think you should be aware if a module cannot be loaded, even if RsaCtfTool is not started in verbose mode.
=> Print warnings even in non-verbose mode.

RsaCtfTool.py, fermat.py
Use gmpy2 isqrt (integer square root) method to speed up the Fermat attack.
$ time ./RsaCtfTool.py --private --verbose -n 25972291333262886126754531447862342318008651545978317992560097655295088183446179998914931077444319512148686227991189070757443095678470077249876125494379543556802873183692990942814980501685535809333479941435337152229473266539872910509228019837179626153738723064214837836127706995237283519368099181137490083783 -e 65537 --attack fermat
Goes from 0m11.640s to 0m0.251s.
Also, reduce the timeout now that we have a much faster attack. Reduce from 60s
to 10s, which makes the attack faster and still allows it to do more
iterations.
Gmpy2 is one of the requirements and RsaCtfTool.py itself also imports it, so
we can assume it is available. This makes the fermat function return …
=> Use gmpy2 isqrt for faster Fermat attack

README.md, RsaCtfTool.py, londahl.py
More details on the algorithm can be found here:
https://grocid.net/2017/09/16/finding-close-prime-factorizations/
This PR fixes issue #59.
We first build a lookup table with `b` entries and then calculate `b` entries
to see if they are in the lookup table. This finds factors if our guess for phi
is at most b^2 away from the actual phi, which gives better results than the
Fermat algorithm.  Increasing b increases memory usage and computation time and
finds primes that are less close to each other. Setting a timeout on this
function is a bad idea, since it will build the lookup table and then abort
while it is using the table.
=> Implement Carl Londahl's factorisation for close p and q

RsaCtfTool.py
If londahl.close_factor doesn't find factors it returns None, and since that
can't be unpacked in p and q it raises a TypeError. Instead of unpacking
directly, first put the factors in the `factors` variable and only unpack them
when it is not None.
=> Fix exception when factor not found in londahl function

smallfraction.sage
Especially, break off the attack once a factor is found. The `break` in the original version only stops the inner loop (num), not the outer loop (den), so
this script would continue searching for a factor.
=> Improve smallfraction attack

README.md, RsaCtfTool.py
In case the modulus N is prime we effectively have one-factor RSA and there is
no security, since phi = n - 1. The tool already handled this case, but this
commit changes the following:
* Separate prime N detection from factordb. Use gmpy2.is_prime to detect
whether N is prime. This makes it possible to run this attack separately and
makes factordb simpler.
* Do our best to create a valid RSA private key. This remains a bit of a hack
since we try to put a single factor into a two-factor key. However, this can
now output a private key that works with OpenSSL.
* Make outputting the key simpler. We used to have either priv_key or
partitial_priv_key, but now we just have one, reducing the complexity in the
output logic.
=> Handle prime N more gracefully

qicheng.sage
So that we don't get a ValueError when we try to parse the sage output as an
integer in the Python script.
=> Print 0 when QiCheng fails

RsaCtfTool.py
Recently I was playing a ctf where n was a square number. I've used your tool many times, as it's easy to go with. So I thought I was giving bad input to the tool, and wasted some time. Later only, I realized that the n provided in the ctf challenge was a square number and your tool doesn't take into account when p=q, thus giving me wrong unciphered text.
=> bug fix for when p is equal to q

partial_q.py
__long__ was removed in Python 3 because all __int__ are of infinite precision.  Discovered via #77
=> Replace long() with int() for Python 3

RsaCtfTool.py
Use ==/!= to compare str, bytes, and int literals.  Discovered via #77 
$ python
```
name = "null"
name += "attack"
name == "nullattack"
>>> True
name is "nullattack"
>>> False
```
=> Identity is not the same thing as equality in Python

README.md
Changing pip to pip3 for installing requirements.txt
=> Python2 is default in MacOS

.github/workflows/lint_python.yml, .travis.yml
Travis CI testing was never turned on at https://travis-ci.com/Ganapati/RsaCtfTool so let's drop Travis and go with builtin GitHub Actions instead.  https://github.com/Ganapati/RsaCtfTool/actions
=> Add a GitHub Action to lint Python

requirements.txt
`pip install gmpy2` fails on Linux and Windows...  See: aleaxit/gmpy#270 
See https://gmpy2.readthedocs.io/en/latest/intro.html#installation for installation on Linux and Windows
=> requirements.txt: GMPY2>=2.1.0b4

requirements.txt
"cryptography" is needed, without it RsaCtfTool can't be executed.
This error message has been shown in Manjaro Linux Distribution. So I think this merge will save a lot of time for many users. :smile: 
```bash
Traceback (most recent call last):
File "RsaCtfTool.py", line 21, in <module>
from lib.rsa_attack import RSAAttack
File "/home/shaswata56/Downloads/challenge/RsaCtfTool/lib/rsa_attack.py", line 7, in <module>
from lib.keys_wrapper import PublicKey
File "/home/shaswata56/Downloads/challenge/RsaCtfTool/lib/keys_wrapper.py", line 10, in <module>
from cryptography.hazmat.primitives import serialization
ModuleNotFoundError: No module named 'cryptography'
```
=> added a valid requirement

attacks/single_key/boneh_durfee.py, attacks/single_key/ecm.py, attacks/single_key/ecm2.py, attacks/single_key/qicheng.py, attacks/single_key/roca.py, attacks/single_key/smallfraction.py, lib/utils.py, path.py
after setting up PATH and wanting to use the tool from elsewhere, sage attacks failed due subprocess launching it from '.'
Added a variable to track where the tool is and thus allowing it to be used anywhere.
=> added path to track root directory of the tool

attacks/multi_keys/commonfactors.py
The trade-of is a little more memory for execution speed.
It can still be improved with batchgcd.
=> commonfactors.py: Execution time O(2n) instead of O(n**2)

attacks/multi_keys/commonfactors.py
Reverts Ganapati/RsaCtfTool#132
I'm sorry it is buged.
=> Revert "commonfactors.py: Execution time O(2n) instead of O(n**2)"

attacks/single_key/factordb.py
without this change factordb responses like `2^4423-1` raise `ValueError: invalid literal for int() with base 10: '2^4423-1'`
=> fix factordb if response in scientific notation

attacks/single_key/siqs.py
The included yafu binary wasn't found.
Btw., your yafu segfaults on my Debian 10 (amd64) machine, so I had to rebuild it. I guess it would be better to look for yafu in $PATH and print a warning if it's not found, instead of including a prebuilt binary.
=> siqs: Fix location of yafu executable

attacks/single_key/z3_solver.py
Both Privatekey and Timeout were needed, but not imported causing import errors. Even after importing them, the s.check() function would cause the script to hang indefinitely.
=> Fixed missing imports and broken timeout

.github/workflows/test.yml
Simply cache the apt (pull, update) process to save time.
=> add cache for tests

README.md, RsaCtfTool.py, lib/idrsa_pub_disector.py
This PR adds the posibility to convert idrsa.pub from ssh to pem format for later attacking.
./RsaCtfTool.py  --convert_idrsa_pub --publickey $HOME/.ssh/id_rsa.pub
private argument is not set, the private key will not be displayed, even if recovered.
Converting /home/dclavijo/.ssh/id_rsa.pub: to pem...
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0svoPrlEHIVaEVfrXVr5
REDACTED
gWpNzo4/8My0xnZgJ4wrm8EzgkGGhJaQAEioFGBFz7C52qV/dgDj2UA6NWU4fntn
nQIDAQAB
-----END PUBLIC KEY-----
=> Add idrsa.pub disector and conversion to pem functionality

RsaCtfTool.py, attacks/single_key/cube_root.py, attacks/single_key/pollard_p_1.py, lib/rsa_attack.py
1. Fixed an exception error on the cube test when the program was run with the parameters "-n" and "-e 3" and no ciphertexts were specified.
2. Fixed an exception when the program was run with "--sendtofdb" and with at least 3 public keys: at least 2 had common factors and at least 1 did not have.
3. Fixed a conversion error/overflow from float to integer.
4. Fixed an exception when the program was run with ciphertexts but without public keys.
=> Fixed multiple run-time exceptions caused by normal command line parameter combinations and normal keys

attacks/single_key/ecm2.py, attacks/single_key/factordb.py, test.sh
```
./RsaCtfTool.py -n 90377629292003121684002147101760858109247336549001090677693 -e 65537 --sendtofdb --private --timeout 100 --attack factordb
[*] Testing key /tmp/tmp3qv1so48.
[*] Performing factordb attack on /tmp/tmp3qv1so48.
Traceback (most recent call last):
File "./RsaCtfTool.py", line 378, in <module>
attackobj.attack_single_key(publickey, attacks_list)
File "/home/max/src/original-github-repo/RsaCtfTool/lib/rsa_attack.py", line 285, in attack_single_key
self.priv_key, unciphered = attack_module.attack(
File "/home/max/src/original-github-repo/RsaCtfTool/attacks/single_key/factordb.py", line 100, in attack
for c in cipher:
TypeError: 'NoneType' object is not iterable
```
=> RsaCtfTool tries to access ciphertexts when they are not needed. This causes TypeError: 'NoneType' object is not iterable

lib/rsalibnum.py
if pow(2,n-1,n) == 1  then n is probable prime and then 
we test it with miller_rabin 
else 
return false because is definitly composite.
We save a lot of time by not running miller_rabin on every number.
The tests I ran are here: https://github.com/daedalus/isprimetimings, 8.07X runtime improvement over miller_rabin alone.
=> Upgrade primality test on non gmpy systems, add fermats prime criterion

README.md
Make sure the `--sendtofdb` option is within the `` `command formatted as code` ``
=> Fix command options formatting typo

.github/workflows/ghcrio_publish.yml
This yml helps to build and publish a docker container to ghcr.io it is triggered with every release.
=> Github container registry publisher action

attacks/single_key/pisano_period.py
* Catch integer overflow so that the tool does not exit the entire process if input is too big
* Minor [PEP 8](https://www.python.org/dev/peps/pep-0008/) changes and optimizations
=> Catch integer overflow

requirements.txt
https://pypi.org/project/pycryptodome/
$ [`safety check`](https://pypi.org/project/safety)
```
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  | …
```
=> requirements.txt: Upgrade insecure pycryptodome

sage/roca_attack.py
The "Fail" return was improperly indented, making the attack stop at the end of the first chunk
=> Fixed roca attack issue

requirements.txt
Related to: https://github.com/Ganapati/RsaCtfTool/issues/289
According to https://www.pycrypto.org/ pycrypto is no longer
maintaned and pycryptodome is a drop-in replacement. (This has
largely been recognized as such for the past few years).
=> Remove pycrypto dependency

README.md, attacks/single_key/nonRSA.py, lib/keys_wrapper.py, lib/rsa_attack.py
I created an attack module to break non RSA keys in the form b^x, with b prime (but also warns if it is not prime).
This should close issues #313 and #286.
I also added an exception handler for KeyboardInterrupt in the principal try catch, so that you can stop an attack if you already know that it won't work, without stopping the whole tool.
=> Add non RSA key attack (n = b^x with b prime)

Dockerfile_full
New Dockerfile that produces an environment containing all optional dependencies such that all RsaCtfTool attacks can be run.
Due to gmp-ecm parameter tuning, I highly recommend manually building this image locally rather than pulling it.
=> Create a secondary Dockerfile with all optional dependencies

RsaCtfTool.py, attacks/multi_keys/common_modulus.py, attacks/multi_keys/same_n_huge_e.py, attacks/single_key/boneh_durfee.py, attacks/single_key/factordb.py, attacks/single_key/small_crt_exp.py, lib/crypto_wrapper.py, lib/keys_wrapper.py, lib/rsa_attack.py, lib/rsalibnum.py
This allows RsaCtfTool to run on vanilla Kali Linux without changing how it runs on any other operating systems
=> wrap cryptodome imports with try/excepts for cryptodomex compat

RsaCtfTool.py, attacks/single_key/factordb.py, lib/keys_wrapper.py, lib/rsa_attack.py
Fixed #338 
- All linting warnings (except those in XYXZ) are lifted
- I feel like it makes more sense to set private key `phi` than directly decrypt ciphertext in the function, but please let me know if that introduces bugs for other attacks. Will change it back.   
- I am not sure what `solveforp` is doing here. Left it as it is for now, but happy to make the function cleaner if someone knows what edge cases the function deals with. 
Sample Output
```
└─$ time ./RsaCtfTool.py -n 25782770308739801605735515865419346856498024381300445265808761658621048766721503037087139898323071038780373167613400772113715669671462708307232644563741556159137258691974660675267505073269223061829358135467419665844389862596565123050172159080698748803875468384311143487369746569113912970383589086725668804617211859 …
```
=> Fix euler's totient in factordb 

attacks/multi_keys/common_modulus.py
When attempting to exploit a common factor in multiple keys with `RsaCtfTool.py --public '*.pub'`, RsaCtfTool crashes with
```
[*] Multikey mode using keys: jiAvqtWm81.pub, pnB2no_G4g.pub, pgcYDb2ltL.pub, _w4AkKhONU.pub, ...
[*] Performing common_modulus attack.
Traceback (most recent call last):
File "/home/cabbache/Desktop/ctftools/RsaCtfTool/RsaCtfTool.py", line 414, in <module>
found = attackobj.attack_multiple_keys(args.publickey, attacks_list)
File "/home/cabbache/Desktop/ctftools/RsaCtfTool/lib/rsa_attack.py", line 233, in attack_multiple_keys
self.priv_key, unciphered = attack_module.attack(
File "/home/cabbache/Desktop/ctftools/RsaCtfTool/attacks/multi_keys/common_modulus.py", line 29, in attack
if len(cipher) < 2:
TypeError: object of type 'NoneType' has no len()
```
This is …
=> Fix crash for --public '*.pub' without --uncipherfile

README.md, optional-requirements.txt, requirements.txt
Easy_install is extremely old and deprecated. In order for clang to properly locate the gmpy header files using homebrew, the prefix is needed. Aditionally, I can't find a method to install the gmpy 1 package on macOS, however as it is a fallback, I would relegate it to the optional-requirements.
=> Improving Mac Compatibility

CHANGELOG.md, CONTRIBUTING.md
I have fixed some typos in markdown files. Following are the fixed typos:
1. informations -> information
2. retreiving -> retrieving
3. Contributons -> Contributions
4. youself -> yourself
I kindly request the repository maintainers to review and merge it. Thanks! :heart:
=> docs: fix typos in markdown files

RsaCtfTool.py
Line 381 of RsaCtfTool.py contains an indentation error. The line contains only a single space instead of a full tab, causing the interpreter to throw the following error:
```
File "/opt/RsaCtfTool/./RsaCtfTool.py", line 381
logger.error("Private key and unciphered data are required.")
```
Line 381 is changed to include a full tab within the uncipher_file() function and fixes this error.
=> updated uncipher_file() at line 381 to fix indentation

RsaCtfTool.py
Fix whitespace before function violating PEP 8 leading to check failures in the following previous commits:
` edefee6, 12c44bc, 6f6b3ae, 56a71b9.`
=> Fix whitespace E 302 (PEP8)

lib/utils.py
As #466 mentioned, SIGALRM is not supported on Windows. I used SIGTERM instead. I have tested on Windows and Linux, both worked.
My testing command is:
`./RsaCtfTool.py --publickey ./examples/elite_primes.pub --private --withtraceback --attack fermat --timeout 3`
`./RsaCtfTool.py --publickey ./examples/fermat.pub --private --withtraceback --attack fermat --timeout 3`
First one will raise timeout in 3 secs, and second one can solve without timeout.
=> fix issue#466

RsaCtfTool.py
Issues resolved:
- When passing `--decryptfile`, the program cannot use provided longs (which was possible before #454 was merged)
- A warning message is always printed when passing `p` and `q` regardless of `n`
=> Fix some issues when longs are provided

README.md
Replaced docker pull command with docker build command because image does not exist on Docker Hub.
=> Updated Docker Section in README

setup.py
Previously, if you tried to install the package using pip it would have:
- A warning regarding a deprecated license ⚠️
- An error preventing the installation 🚨
Additionally, I added a feature, when the package is installed it can be accessed through 2 CLI commands:
- rsa
- rsaCtfTool
=> Fix(setup.py) add support for pip install .

Dockerfile
script has been renamed and is (now?) located in the `src/RsaCtfTool` subdirectory
=> fix: Update Dockerfile with new script name (+pathfix)

setup.py, src/RsaCtfTool/attacks/single_key/pastctfprimes.py, src/RsaCtfTool/lib/algos.py, src/RsaCtfTool/lib/external.py, src/RsaCtfTool/lib/number_theory.py, src/RsaCtfTool/lib/rsa_attack.py, src/RsaCtfTool/lib/system_primes.py, src/RsaCtfTool/lib/utils.py
This PR includes fxes for 51x linter issues [flagged in CI](https://github.com/RsaCtfTool/RsaCtfTool/actions/runs/14247924835/job/39933475095):
* Formatted files containinf 44x whitespace issues (below) using [Black](https://pypi.org/project/black/)
* 5     E111 indentation is not a multiple of 4
* 10    E225 missing whitespace around operator
* 7     E226 missing whitespace around arithmetic operator
* 7     E231 missing whitespace after ','
* 6     E261 at least two spaces before inline comment
* 2     E262 inline comment should start with '# '
* 1     E265 block comment should start with '# '
* 1     E275 missing whitespace after keyword
* 3     E303 too many blank lines (3)
* 1     E306 expected 1 blank line before a nested definition, found 0
* 1     W293 blank line contains …
=> Adjust code-style, per flags from flake8 linter runs in CI
