RsaCtfTool/RsaCtfTool

optional-requirements.txt, requirements.txt
updated requirements.txt and added optional-requirements.txt file for install of SageMath
=> Updated requirements

RsaCtfTool.py
This change makes the script work inside virtual environments
=> Change shabang to /usr/bin/env python

RsaCtfTool.py
sageversion is a byte type variable, so decode it first
=> update check for sageversion

RsaCtfTool.py
Read n and/or e from publickey file.
If only one of p and q is given, calculate the other.
=> Read and calculate key info if possible

RsaCtfTool.py
factordb.com is now supporting TLS-connections
=> Use https when checking factordb.com

LICENSE.md
Created a official lincense.md file, for those who want it in black in white :)
=> Created a LICENSE.md, closes #50

README.md
Updated readme instructions to create a virtual environment as projects uses python2
=> Update Readme for Kali/Ubuntu Instructions

primefac.py
=> Convert from xrange() --> range() and remove unused imports

.travis.yml
The repo switch would need to be turned on at https://travis-ci.com/Ganapati/RsaCtfTool to enable free, automated testing of all code changes.
=> Add automated testing with Travis CI

RsaCtfTool.py
It's difficult to know whether the driver script is detecting your sagemath installation. Added some print statements to show SageMath status
=> Print SageMath detection status 

primefac.py
Use explicit imports to fix the remaining flake8 undefined names.
=> Fix remaining flake8 undefined names

sage/qicheng.sage
This will allow qicheng factoring in a faster way
=> qicheng.sage: run attempts in parallel up to cpu_count

attacks/single_key/factordb.py
- Added check if `p` and `q` from factordb multiplied equals to `n`
- Based on issue #129
=> #129 Check if factordb p and q product is n

README.md, attacks/single_key/binary_polinomial_factoring.py, sage/binary_polinomial_factoring.sage
Convert an integer to a polynomial in powers of 2.
Factor the polynomial with sage built-in factor function.
Eval the resulting polymonials with x=2.
Find factors.
=> attack: Factoring integers representing them with polynomials with order=bits

README.md, attacks/single_key/euler.py
While Fermat’s method requires the two prime factors to be relatively close to each other.
Euler’smethod is more efficient than Fermat’s due to its ability to be used as long as you
can find representations of the integers as sums of two squares.
Euler’s factorization method works by factoring an integer by
writing it as a sum of two different sets of two squares.
Ex: 100009 = 1000 ^ 2 + 3 ^ 2 = 972 ^ 2 + 235 ^ 2 .
Worst execution time: O(sqrt(N))
=> Euler method

README.md, RsaCtfTool.py, lib/fdb.py, lib/rsa_attack.py
optionaly send factorization results to factordb
=> Send results to factordb

.github/workflows/codeql.yml, README.md
This github-action will run a cronified vulnerability and code quality assesment.
more info: https://github.com/github/codeql-action
=> Actions:CodeQL 

.github/workflows/codeql.yml
=> Small fix:Update codeql.yml

RsaCtfTool.py
I forgot to add the code in the main script.
Now it should work.
=> Update RsaCtfTool.py: conspicuousness check

attacks/single_key/fermat_numbers_gcd.py, attacks/single_key/mersenne_pm1_gcd.py, attacks/single_key/primorial_pm1_gcd.py
Test run was ok
Test fermat numbers gcd
[*] Testing key examples/fermat_numbers_gcd.pub.
[*] Performing fermat_numbers_gcd attack on examples/fermat_numbers_gcd.pub.
0%|                                                                                                                                         | 0/9999 [00:00<?, ?it/s]
Results for examples/fermat_numbers_gcd.pub:
Private key :
-----BEGIN RSA PRIVATE KEY-----
MIIBJQIBAAJDTuJNJVnOa1qp8n91iIWs30F6xA+I/nkfMV7Ad/0M5seWOKImUngY
ig60DRfrXwXa7GWh8qmK0V5sR+ib27+bbZfwAQIDAQABAkMBYQAeoKAOTSdrXCie
mlExr3m8TTxrAyY1PR+TX8XTj7Zjuj6xPyguqAZXTdoiokrElxvQzuXktjtuUyj/
5/mJKn7BAkMPxtw6q4+vEiH9TLEbTe9f2eVaaYHMfp/WrIzkzDXHwYRxugeqGATo
aVc10ZV5Z5IvR4bKIeiQRhWn+1JfJlJJHmMzAgEFAkMBYQAeoKAOTSdrXCiemlEx …
=> add missing tqdm to PR #173

attacks/single_key/fibonacci_gcd.py
Test ran ok
[*] Testing key examples/fibonacci_gcd.pub.
[*] Performing fibonacci_gcd attack on examples/fibonacci_gcd.pub.
11%|████████████████                                                                                                                                 | 1110/9999 [00:00<00:00, 187630.57it/s]
Results for examples/fibonacci_gcd.pub:
Private key :
-----BEGIN RSA PRIVATE KEY-----
MIICOQIBAAJ5C/QyoZTftkv7F7HOOWqxiRTnW3SamWXYEKiCOio1vK3Xh/HMJdJZ
5JsOwd27OTvlBw5eLEjsJfjT0PQR/ULJujjvf35q4EYr3aw1U4JVcy8h2eyb61Ah
NDc1GL2YXOIkjUbpj+8I0fKpDjPesfa0h5yhTluox5AlBQIDAQABAnkJZNg9Hq9H
pSInlrVHbc8iuOiveEzd66kGPkZIy077fWn5DU2vE0VNX4UTWNp+udDb4LClAJGD
ra1XRLgg2DgpTyv90uyt5IZUX3FRM83TceCUKQgvvvWMwqyxGGnMwT6Hw97Qvgc7
Z2Tv/OS6NMBUDCA7AZN3oKtBAj85ag1TC9cj9i94DFOP06JFloCRC/HY3C0GV/WY …
=> small bugfix

attacks/multi_keys/commonfactors.py
This PR improves the commonfactors attack upper time boundary from O(n^2) to O(2n), by using a product tree and computing the remainder in every publick key.
The tradeoff is memory versus time.
Test ran ok
./RsaCtfTool.py --public "examples/commonfactor*.pub" --attack commonfactors --private
[*] Multikey mode using keys: examples/commonfactor7.pub, examples/commonfactor6.pub, examples/commonfactor4.pub, examples/commonfactor5.pub, examples/commonfactor8.pub, examples/commonfactor9.pub, examples/commonfactor10.pub, examples/commonfactor3.pub, examples/commonfactor11.pub, examples/commonfactor1.pub, examples/commonfactor12.pub, examples/commonfactor2.pub
[*] Performing commonfactors attack.
[*] Found common factor in modulus for examples/commonfactor8.pub
[*] Found common factor in modulus …
=> Improved execution time boundary: O(2n) instead of O(n^2)

README.md, RsaCtfTool.py, lib/rsa_attack.py
Solve https://github.com/Ganapati/RsaCtfTool/issues/193
=> Implement option to specify multiple attacks

.github/workflows/test.yml
=> Add a GitHub workflow for testing

.github/workflows/pypi-publish.yml, setup.py
Only need to setup your pypi credentials in the repo->settings->secrets
PYPI_PASSWORD
PYPI_USERNAME
Then on every release it will automaticaly send a push to pypi
=> pypi publish workflow

RsaCtfTool.py, lib/idrsa_pub_disector.py
./RsaCtfTool.py --convert_idrsa_pub --publickey /home/dclavijo/.ssh/known_hosts 
private argument is not set, the private key will not be displayed, even if recovered.
Converting /home/dclavijo/.ssh/known_hosts: to pem...
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEAq2A7hRGmdnm9tUDbO9ID
_REDACTED_
HSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFA
aQIBIw==
-----END PUBLIC KEY-----
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEAq2A7hRGmdnm9tUDbO9ID
_REDACTED_
HSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFA
aQIBIw==
-----END PUBLIC KEY-----
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEAq2A7hRGmdnm9tUDbO9ID
_REDACTED_
HSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFA …
=> Multiple file idrsa dissection, idrsa dissector now supports knownhosts file

.github/workflows/test.yml
Try to catch opportunities to cache pip workdir and apt /var/cache/apt/.
=> Try to cache explicitly apt and pip

requirements.txt
The dependency should be bitarray and not bytearray.
=> fix pypi dependencies

attacks/single_key/SQUFOF.py
- Avoid recomputing things
- PEP8 compliant
- Fix testcase
=> Squfof performance update

lib/rsa_attack.py
On some systems this pre checks are not needed but in others they may catch some errors in malformed public rsa keys.
Check public key modulus:
- Is odd
- Is not a perfect square
- Does not share a factor with exponent
- Is not prime
- Is > 3
=> Pre checks

lib/fdb.py
Get rid of factordb misleading reply when no new factors(to them) are found.
This solves the issue #234.
=> Get rid of factordb misleading reply 

attacks/single_key/fermat.py
- More compact version
- Easy to undersand
- Less wasteful
- Avoid computing isqrt two times
Test ran ok
./RsaCtfTool.py --attack fermat --test
[*] Testing fermat
[*] Success
=> Update fermat attack

attacks/multi_keys/hastads.py, attacks/single_key/cube_root.py, attacks/single_key/dixon.py, attacks/single_key/ecm2.py, attacks/single_key/factordb.py, attacks/single_key/londahl.py, attacks/single_key/pollard_p_1.py, lib/keys_wrapper.py, sage/roca_attack.py, sage/small_crt_exp.sage
This pr refers to issue #235 wich is a real speed enhancement.
=> s/pow/powmod/g, use gmpy2.powmod instead of native pow implementation

README.md, RsaCtfTool.py, lib/rsa_attack.py
Solves Issue #243 by adding a switch (--ignore_checks) to ignore the pre attack checks for malformed modulus.
=> solve Issue 243: add ignore_checks switch

RsaCtfTool.py
`priv_key.decrypt` receives a cipher text or a cipher list, and return a plain text list.
=> fix error caused by the nested list

README.md, attacks/single_key/pisano_period.py, lib/rsalibnum.py
Optimal algorithm for sub 47 bits, factors in less than a minute.
Other integer sizes remain to be tested.
=> Add pisano period integer factorization algorithm

attacks/single_key/pisano_period.py, lib/rsalibnum.py, lib/utils.py
20x speedup, 
Factotization from 47 to 70 bit in less than a minute with Intel(R) Xeon(R) CPU  E5640  @ 2.67GHz
Search space: B1=10**6
=> Pisano period attack improvements

attacks/single_key/pisano_period.py
Use a dictionary based lookup table instead of a binary search over a list.
=> Use dictionary lookup table instead of binary_search

attacks/single_key/neca.py, lib/external.py
Create a lib for external programs.
move neca attack to the external programs lib.
=> External programs

lib/rsa_attack.py
=> Catches unhandled exceptions during attacks

attacks/single_key/XYXZ.py
* Work up to max_power = (log base of n) / 2
* Work with various bases.
=> XYXZ improvements

README.md, attacks/single_key/highandlowbitsequal.py
Factors n = p*q if p and q share sufficiently many high and low bits.
=> HighandLowBitsEqual attack

lib/utils.py
Added code to try decoding PKCS#1.5 padding on the result of unciphered files.
=> add PKCS#1.5 padding decoding

RsaCtfTool.py, attacks/multi_keys/hastads.py, lib/number_theory.py, lib/rsa_attack.py
I noticed that even if tests where implemented on multikey attacks, they are never called.
Hastads attack had been broken for a long time (see issue #307 ) and now it should be fixed.
=> Multi key tests and hastads attack fix

lib/number_theory.py, lib/utils.py
Ran into the same issue as #392 and figured I might as well share my local fix.
I saw there was some blackifying taking place in the git history, so I took the opportunity to blacken the two affected files as well (hence the other edits).
Thanks for a great tool!
=> Quickfix on broken all/any

RsaCtfTool.py
Added the information what unit timeout has, what max. and min. values are to not getting an exception and what the effect of setting it to <= 0 seems to be.
=> Added some information to the helptext of timeout

README.md
Fixed all the typos and punctuations and corrected all the grammatical errors in README.md
=> docs: corrected all the grammatical errors in README.md

CODE_OF_CONDUCT.md
Fixed Issue #437 Kindly review It
=> Added CODE_OF_CONDUCT.md in repo

README.md
Fixed Issue #438 
@daedalus Kindly review the PR. Thank You !
=> Updated Contributors Section in readme

RsaCtfTool.py, lib/utils.py
Improve `--dumpkey` display in case private key is found and remove unused parameter `--show-factors`
=> Improve dumpkey

attacks/abstract_attack.py
Type Annotations: Function parameters and return types are annotated to improve code readability and type checking.
Default Arguments: The cipher parameter now has a default value of None and is properly handled inside the attack() method.
Logger Configuration: The logger is configured using basicConfig() with a specific log level (INFO) and format.
Constants: SPEED_ENUM is defined as a class constant.
=> Updated abstract_attack.py

attacks/single_key/pollard_p_1.py
Pollard_p_1 attack is currently broken since commit 3858cf5. 
pp should be updated in each loop so it becomes prime ** (product of all primes < bound)
=> Fix pollard_p_1 Attack

.github/workflows/codeql.yml, .github/workflows/ghcrio_publish.yml, .github/workflows/lint_python.yml, .github/workflows/pypi-publish.yml, .github/workflows/test.yml, attacks/single_key/euler.py, attacks/single_key/lehmer.py, attacks/single_key/pisano_period.py, lib/algos.py, lib/number_theory.py
Update GitHub Actions to latest versions & more linter fixes
=> Update GitHub Actions to latest versions & more linter fixes

RsaCtfTool.py
This pull request aims to restore the functionality of the `--decryptfile` option with public keys in the decrypt_file function. Previously, this functionality was present but became non-functional over time. Additionally, this change acknowledges that decryption using private keys may not currently work correctly. (Not sure tho)
- Modified the decrypt_file function to allow decryption with a private key and to prepare files for decryption with a public key.
- Added a note in the function's docstring indicating that decryption with a private key may not work correctly at the moment.
**Issue Reference**: Fixes #472 
Please review and consider merging these changes into the main codebase. Thank you!
=> Restore --decryptfile functionality with public keys

Dockerfile, Dockerfile_full, requirements.txt
[`gmpy2` >=2.2.0 will allow latest Python version.](https://github.com/aleaxit/gmpy?tab=readme-ov-file#gmpy2-220)
=> Bump gmpy2 version and use python docker base image
